server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/network
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
