server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://database:5432/network
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://network-discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
